### ISSUE TITLE
qBittorrent 4.5.0 broken

### ISSUE THREAD

**Issue by tordenflesk** [GilbN/theme.park#458]
**Describe the bug**
https://i.imgur.com/d43BSh4.png

**Comment by GilbN** [comment]
Upstream issue nothing I can do.

**Comment by alchemist-zim** [comment]
So this is a qbitorrent issue, and not a theme.park issue?

**Comment by tordenflesk** [comment]
Disabling the theme returns the UI to normal.

**Comment by sledgehammer999** [comment]
As per https://github.com/qbittorrent/qBittorrent/issues/18109#issuecomment-1331832643

With PR https://github.com/qbittorrent/qBittorrent/pull/17616 only the builtin WebUI gets translated. The builtin WebUI uses this construct `QBT_TR(string)QBT_TR[CONTEXT=context]` to denote translatable strings to the server (qbt). With 4.5.0 the server does the translation only for the buildin webui.

As a fix you should apply a search+replace regex on all copied files.
These two regexes match the expression
```
QBT_TR\((.*)\)QBT_TR\[CONTEXT=context\]
QBT_TR\((.*)\)QBT_TR
```

and capture the translatable string in the 1st capturing group. Then use `\1` or `$1` to replace/substitute it.

ATTENTION: Apply the first regex before the second one, otherwise it won't work.

**Comment by MahdiMirzade** [comment]
I think this regex is better: (as explained in https://github.com/qbittorrent/qBittorrent/issues/18109#issuecomment-1331968228)
```
QBT_TR\((([^\)]|\)(?!QBT_TR))+)\)QBT_TR\[CONTEXT=([a-zA-Z_][a-zA-Z0-9_]*)\]
```
But both solutions won't work for strings which are combined by a number or another string.

**Comment by GilbN** [comment]
Please try `ghcr.io/gilbn/theme.park:qbittorrent-regex` or https://github.com/GilbN/theme.park/blob/develop/docker-mods/qbittorrent/root/etc/cont-init.d/98-themepark if you use the hotio image

**Comment by tordenflesk** [comment]
menus are still a mess, but looks good otherwise
![image](https://user-images.githubusercontent.com/2136727/208746790-9073ed96-026b-4c87-a2a3-5313be67976d.png)

**Comment by GilbN** [comment]
Re

> menus are still a mess, but looks good otherwise ![image](https://user-images.githubusercontent.com/2136727/208746790-9073ed96-026b-4c87-a2a3-5313be67976d.png)

Restart the container

**Comment by tordenflesk** [comment]
Just saw the message about that in the log now. all good now.

**Comment by GilbN** [comment]
Merged to master

**Comment by hugalafutro** [comment]
Hi 
everything works great with the `-regex` theme

Is the theme gonna be called `ghcr.io/gilbn/theme.park:qbittorrent-regex` from now on, or is it at some point gonna get merged into master and we should revert back to `ghcr.io/gilbn/theme.park:qbittorrent`? If so how would I track when that happens? 

Thanks!
